29: Add sidecar's for application ELK logging
NationalSecurityAgency/datawave-ingest-services pull request #34
Opened 2023-04-26 01:43 UTC by cfkoehler

I am open to suggestions to reduce the duplication of config map's. I tried moving them to the common library but they could not have data defined and without that did not see a point in having them in the library just to consume the metadata portion.

2023-04-28 00:23 UTC, FineAndDandy commented on bundler/src/main/chart/templates/daemonset.yaml
> +          image: "{{ $.Values.filebeat.imageRepo }}:{{ $.Values.filebeat.imageTag }}"
it would be nice if the image had the same layout as all the other images in the repo

2023-04-28 00:24 UTC, FineAndDandy commented on bundler/src/main/chart/templates/daemonset.yaml
> +              mountPath: "/usr/share/filebeat/{{ $.Values.filebeat.pipelineDestDir }}"
can these be standardized to the common.volumeMount?

2023-04-28 00:25 UTC, FineAndDandy commented on bundler/src/main/chart/templates/daemonset.yaml
> +              mountPath: "/usr/share/logstash/{{ $.Values.logstash.pipelineDestDir }}"
please standardize

2023-04-28 00:29 UTC, FineAndDandy commented on bundler/src/main/chart/templates/daemonset.yaml
please use common volumes, mounts, and image patterns

2023-04-28 00:29 UTC, FineAndDandy commented on feeder/src/main/chart/templates/deployment.yaml
please use common volumes, mounts, and image patterns

2023-04-28 00:30 UTC, FineAndDandy commented on ingest/src/main/chart/templates/deployment.yaml
please use common volumes, mounts, and image patterns

2023-04-28 00:36 UTC, FineAndDandy requested changes
Ideally I'd like to see the filebeat/logstash and base config packed into an image that would work with minimal env/mounts on all containers that we want to include this on. Then we mount in any specialized config for the container if it exists. I think it could be out of scope for this effort though. 

To keep the charts consistent it would be nice if you used the common templates and patterns where possible.

2023-05-01 16:51 UTC, magrable commented
2 comments on moving config to an image:
1) Right now the configs are largely the same for all services, but they will start diverging (eg. no logstash)
2) One of my requirements was that the config could be updated without restarting the application - that is achievable with the way the volumes are mounted.  If we remove these volumes, we'll need to maintain a way to edit the config without causing application restart

I agree that right now there is tons of duplication between helm charts that use these sidecars, but we have problems to work through before we remove these patterns.

2023-05-08 09:32 UTC, closed without merging