SONAR:: Simple Sonar changes to SplitConsumer.java
NationalSecurityAgency/datawave-ingest-services pull request #41
Opened 2023-05-17 01:04 UTC by cfkoehler

2023-05-18 13:00 UTC, apmoriarty approved these changes

2023-05-18 13:43 UTC, drewfarris approved these changes

2023-05-18 14:19 UTC, cfkoehler commented on ingest/src/main/java/datawave/microservice/ingest/messaging/SplitConsumer.java
> +                log.info("Completed uuid: {} attempt: {} file: {} in {}ms", messageUuid, attempt, fileSplit.getPath(), duration);
```suggestion
                log.info("Completed uuid: {} attempt: {} file: {} in {} ms", messageUuid, attempt, fileSplit.getPath(), duration);
```

2023-05-24 01:57 UTC, jpdahlke requested changes

2023-05-24 01:57 UTC, jpdahlke commented on ingest/src/main/java/datawave/microservice/ingest/messaging/SplitConsumer.java
> +                    log.warn("Failed to process ingest for split: {}" + fileName, e);
```suggestion
                    log.warn("Failed to process ingest for split: {}", fileName, e);
```

2023-05-24 03:04 UTC, magrable submitted a review, later dismissed

2023-05-24 08:53 UTC, apmoriarty approved these changes

2023-05-24 15:17 UTC, jpdahlke approved these changes

2023-05-24 16:11 UTC, merged